### ISSUE TITLE
Saving a config with invalid JSON shouldn't reset it.

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#10]
When enter a json in the config via UI and make a typo it wan't save my changes which is annoying.
![image](https://user-images.githubusercontent.com/4261252/42911027-063f33ea-8aaf-11e8-863b-ed839de04227.png)

**Comment by wasimpathan5** [comment]
Fixed. Pull request: https://github.com/ZS/powergrid/pull/17
