### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by wasimpathan5** [ZS/powergrid#19]
Created this issue just for sake of storing the images. So that, we can use their URLs to construct our wiki pages ;)

![image](https://user-images.githubusercontent.com/3293662/43142489-236b0a5e-8f76-11e8-9cfe-96e387c4e22e.png)

**Comment by wasimpathan5** [comment]
![image](https://user-images.githubusercontent.com/3293662/43142672-907008c0-8f76-11e8-8fde-8574642fddf2.png)

**Comment by wasimpathan5** [comment]
![image](https://user-images.githubusercontent.com/3293662/43142979-5ca9640e-8f77-11e8-85b6-8ae62bd99eea.png)

**Comment by php1990** [comment]
![image](https://user-images.githubusercontent.com/37831642/43311461-2b369bac-91a8-11e8-8847-6e961b45a6a9.png)
