### ISSUE TITLE
Let explicitly position items in rows or columns we don't define in the grid.

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#20]
Use this [configuration](https://zs.github.io/powergrid/?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyJtaW5tYXgobWluLWNvbnRlbnQsMWZyKSIsIm1pbm1heChtaW4tY29udGVudCwxZnIpIiwibWlubWF4KG1pbi1jb250ZW50LDFmcikiXSwicm93cyI6WyJtaW5tYXgobWluLWNvbnRlbnQsIDIwMHB4KSJdLCJjZWxscyI6W3sidGV4dCI6IkJpZy1pbWFnZSIsImNvbFNwYW4iOjJ9LHsidGV4dCI6IlNtYWxsLWltYWdlIiwiY29sIjozfSx7InRleHQiOiJTbWFsbC1pbWFnZSIsImNvbCI6MSwicm93IjoyfSx7InRleHQiOiJCaWctaW1hZ2UiLCJjb2wiOjIsImNvbFNwYW4iOjIsInJvdyI6Mn1dLCJwcmVmaXgiOiJwZy0ifQ==)

Observe that even if we want to explicitly place a grid item into second row it is forced to be in the first row. 

![image](https://user-images.githubusercontent.com/4261252/43165842-8a887dd2-8f5a-11e8-9659-5fa63f0c67bc.png)

It could be useful for some cases like unknown number of rows.

**Comment by parulM1992** [comment]
https://github.com/ZS/powergrid/pull/35 pull request created for this.
