### ISSUE TITLE
Fill the gaps in the community check list

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#36]
https://github.com/ZS/powergrid/community
* Code of conduct
* Issue templates
* Pull request template

**Comment by php1990** [comment]
Added:
- Code of conduct
- Issue templates
- Pull request template

https://github.com/ZS/powergrid/blob/master/CODE_OF_CONDUCT.md
https://github.com/ZS/powergrid/blob/master/PULL_REQUEST_TEMPLATE.md
https://github.com/ZS/powergrid/blob/master/.github/ISSUE_TEMPLATE/feature_request.md
https://github.com/ZS/powergrid/blob/master/.github/ISSUE_TEMPLATE/report-a-bug.md
